# This is the configuration file for GitHub's Dependabot, used here for version updates.
# See the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # All GitHub actions should be pinned to an explicit SHA instead of a tag name.
  # Each pin should include a comment about the version of the action to which it corresponds.
  # Dependabot will update these comments at the same time that it updates the pin.
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
