name: Build and Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - '*'

permissions:
  contents: write
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [arm64, amd64]

    steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

    - name: Pull Docker Image for ${{ matrix.arch }}
      run: |
        docker pull --platform linux/${{ matrix.arch }} ejortega/milkv-host-tools:latest

    - name: Run Docker Container and Extract Toolchain
      run: |
        container_id=$(docker create ejortega/milkv-host-tools:latest) && \
        docker cp $container_id:/app/riscv64-unknown-linux-musl.tar.xz riscv64-unknown-linux-musl-${{ matrix.arch }}.tar.xz && \
        docker rm $container_id

    - name: Upload Artifact for ${{ matrix.arch }}
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.0
      with:
        name: riscv-toolchain-${{ matrix.arch }}
        path: riscv64-unknown-linux-musl-${{ matrix.arch }}.tar.xz

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Download ARM Artifacts
      uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4.2.1
      with:
        name: riscv-toolchain-arm64
        path: ./artifacts

    - name: Download AMD Artifacts
      uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4.2.1
      with:
        name: riscv-toolchain-amd64
        path: ./artifacts

    - name: Create Release
      uses: ncipollo/release-action@440c8c1cb0ed28b9f43e4d1d670870f059653174 # v1.16.0
      with:
        artifacts: |
          ./artifacts/riscv64-unknown-linux-musl-arm64.tar.xz
          ./artifacts/riscv64-unknown-linux-musl-amd64.tar.xz
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
        name: ${{ github.ref_name }}
        allowUpdates: true
        replacesArtifacts: true
        body: |
          This release contains the toolchain tarballs for both ARM64 and AMD64 architectures.
